-- MySQL Script generated by MySQL Workbench
-- Wed Apr 28 12:14:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coronavacination
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `coronavacination` ;

-- -----------------------------------------------------
-- Schema coronavacination
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coronavacination` DEFAULT CHARACTER SET latin1 ;
USE `coronavacination` ;

-- -----------------------------------------------------
-- Table `coronavacination`.`Vaccines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coronavacination`.`Vaccines` ;

CREATE TABLE IF NOT EXISTS `coronavacination`.`Vaccines` (
  `vaccinationTypeID` INT NOT NULL,
  `vaccinationTypeName` VARCHAR(45) NULL,
  `vaccinePrice` INT NULL,
  PRIMARY KEY (`vaccinationTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coronavacination`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coronavacination`.`Person` ;

CREATE TABLE IF NOT EXISTS `coronavacination`.`Person` (
  `cpr` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Vaccines_vaccinationTypeID` INT NOT NULL,
  PRIMARY KEY (`cpr`),
  INDEX `fk_Person_Vaccines1_idx` (`Vaccines_vaccinationTypeID` ASC) VISIBLE,
  CONSTRAINT `fk_Person_Vaccines1`
    FOREIGN KEY (`Vaccines_vaccinationTypeID`)
    REFERENCES `coronavacination`.`Vaccines` (`vaccinationTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coronavacination`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coronavacination`.`Employee` ;

CREATE TABLE IF NOT EXISTS `coronavacination`.`Employee` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `salary` INT NULL,
  `employmentType` VARCHAR(45) NULL,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coronavacination`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coronavacination`.`Location` ;

CREATE TABLE IF NOT EXISTS `coronavacination`.`Location` (
  `deptName` VARCHAR(45) NOT NULL,
  `Employee_employeeID` INT NOT NULL,
  PRIMARY KEY (`deptName`),
  INDEX `fk_Location_Employee1_idx` (`Employee_employeeID` ASC) VISIBLE,
  CONSTRAINT `fk_Location_Employee1`
    FOREIGN KEY (`Employee_employeeID`)
    REFERENCES `coronavacination`.`Employee` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coronavacination`.`VaccinationAppointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coronavacination`.`VaccinationAppointment` ;

CREATE TABLE IF NOT EXISTS `coronavacination`.`VaccinationAppointment` (
  `Person_cpr` INT NOT NULL,
  `Vaccines_vaccinationTypeID` INT NOT NULL,
  `Employee_employeeID` INT NOT NULL,
  `vaccinationDate` INT NULL,
  `vaccinationTime` INT NULL,
  `Location_deptName` VARCHAR(45) NOT NULL,
  INDEX `fk_VacinationAppointment_Person_idx` (`Person_cpr` ASC) VISIBLE,
  INDEX `fk_VaccinationAppointment_Vaccines1_idx` (`Vaccines_vaccinationTypeID` ASC) VISIBLE,
  INDEX `fk_VaccinationAppointment_Employee1_idx` (`Employee_employeeID` ASC) VISIBLE,
  INDEX `fk_VaccinationAppointment_Location1_idx` (`Location_deptName` ASC) VISIBLE,
  CONSTRAINT `fk_VacinationAppointment_Person`
    FOREIGN KEY (`Person_cpr`)
    REFERENCES `coronavacination`.`Person` (`cpr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VaccinationAppointment_Vaccines1`
    FOREIGN KEY (`Vaccines_vaccinationTypeID`)
    REFERENCES `coronavacination`.`Vaccines` (`vaccinationTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VaccinationAppointment_Employee1`
    FOREIGN KEY (`Employee_employeeID`)
    REFERENCES `coronavacination`.`Employee` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VaccinationAppointment_Location1`
    FOREIGN KEY (`Location_deptName`)
    REFERENCES `coronavacination`.`Location` (`deptName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coronavacination`.`Certifcates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coronavacination`.`Certifcates` ;

CREATE TABLE IF NOT EXISTS `coronavacination`.`Certifcates` (
  `Employee_employeeID` INT NOT NULL,
  `certificationDate` INT NULL,
  `Vaccines_vaccinationTypeID` INT NOT NULL,
  INDEX `fk_Certifcates_Employee1_idx` (`Employee_employeeID` ASC) VISIBLE,
  INDEX `fk_Certifcates_Vaccines1_idx` (`Vaccines_vaccinationTypeID` ASC) VISIBLE,
  CONSTRAINT `fk_Certifcates_Employee1`
    FOREIGN KEY (`Employee_employeeID`)
    REFERENCES `coronavacination`.`Employee` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Certifcates_Vaccines1`
    FOREIGN KEY (`Vaccines_vaccinationTypeID`)
    REFERENCES `coronavacination`.`Vaccines` (`vaccinationTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coronavacination`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coronavacination`.`Inventory` ;

CREATE TABLE IF NOT EXISTS `coronavacination`.`Inventory` (
  `Location_deptName` VARCHAR(45) NOT NULL,
  `Vaccines_vaccinationTypeID` INT NOT NULL,
  `inventory` INT NULL,
  INDEX `fk_Inventory_Vaccines1_idx` (`Vaccines_vaccinationTypeID` ASC) VISIBLE,
  INDEX `fk_Inventory_Location1_idx` (`Location_deptName` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_Vaccines1`
    FOREIGN KEY (`Vaccines_vaccinationTypeID`)
    REFERENCES `coronavacination`.`Vaccines` (`vaccinationTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventory_Location1`
    FOREIGN KEY (`Location_deptName`)
    REFERENCES `coronavacination`.`Location` (`deptName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
